'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("LibraSys.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _1__The_winter_s_tale__Author__William_Shakespeare() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1. The winter's tale, Author_ William Shakespeare", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _12__Roman_history__Author__Titus_Livius() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("12. Roman history, Author_ Titus Livius", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _121() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("121", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _13__History_of_the_Peloponnesian_war__Author__Thucydides() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("13. History of the Peloponnesian war, Author_ Thucydides", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _6_The_history_of_Herodotus__Author__Herodotus() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("6 The history of Herodotus, Author_ Herodotus", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _6_The_history_of_Herodotus__Author__Herodotus1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("6 The history of Herodotus, Author_ Herodotus1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _9__The_Arte_of_Warre__Author__Niccolò_Machiavelli() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("9. The Arte of Warre, Author_ Niccolò Machiavelli", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _91() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("91", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ADMINHOMEPAGE() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ADMINHOMEPAGE", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ARCHIVESANDLIST() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ARCHIVESANDLIST", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ARCHIVESANDLIST1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ARCHIVESANDLIST1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property BORROWCONFIRMATION() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BORROWCONFIRMATION", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property BORROWING() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BORROWING", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property BORROWING1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BORROWING1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property GUESTMODE() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("GUESTMODE", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property LOADING() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LOADING", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property LOADING1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LOADING1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property LOGINPAGE() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LOGINPAGE", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MAINPAGE() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MAINPAGE", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MAINPAGE1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MAINPAGE1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MAINPAGE2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MAINPAGE2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MAINTENANCE() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MAINTENANCE", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property NAVBAR() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("NAVBAR", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property RESERVATION() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("RESERVATION", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TRANSACTION() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TRANSACTION", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property UserList() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("UserList", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property USERNAVBAR() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("USERNAVBAR", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property USERNAVBAR1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("USERNAVBAR1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property USERNAVBAR2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("USERNAVBAR2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property WELCOME_PAGE() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("WELCOME PAGE", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property WELCOMEPAGE() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("WELCOMEPAGE", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property WELCOMEPAGE__2_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("WELCOMEPAGE (2)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property WELCOMEPAGE1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("WELCOMEPAGE1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property WELCOMEPAGE2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("WELCOMEPAGE2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property WELCOMEPAGE3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("WELCOMEPAGE3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property WELECOME() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("WELECOME", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
